spring:
  application:
    name: cloudbox-storage-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

storage:
  minio:
    endpoint: ${MINIO_ENDPOINT}
    username: ${MINIO_USERNAME}
    password: ${MINIO_PASSWORD}
    region: ${MINIO_REGION}
    bucket-name: ${MINIO_BUCKET_NAME}